name: CI Pipeline

on:
  push:
    branches: [ main, develop ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    name: Test on Node.js ${{ matrix.node-version }}
    runs-on: ubuntu-latest
    
    strategy:
      matrix:
        node-version: [18.x, 20.x]

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Setup Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v4
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'

    - name: Install dependencies
      run: npm install

    - name: Run tests
      run: npm test

    - name: Verify build
      run: |
        npm start &
        SERVER_PID=$!
        sleep 5
        curl -f http://localhost:3000/ || echo "Root endpoint check failed"
        curl -f http://localhost:3000/health || echo "Health endpoint check failed"
        kill $SERVER_PID
        echo "✅ Build verification completed"
